[font]
size = 14
offset = { x = 0, y = 1 }

[font.normal]
family = "IosevkaRakesh Nerd Font"

[font.bold]
family = "IosevkaRakesh Nerd Font"

[font.italic]
family = "IosevkaRakesh Nerd Font"

[font.bold_italic]
family = "IosevkaRakesh Nerd Font"
