[font]
size = 14
# offset = { x = 0, y = 3 }


[font.normal]
# family = "IosevkaRakesh Nerd Font"
family = "Annotation Mono"
style = "Regular"

[font.bold]
# family = "IosevkaRakesh Nerd Font"
family = "Annotation Mono"
style = "Regular"

[font.italic]
# family = "IosevkaRakesh Nerd Font"
family = "Annotation Mono"
# family = "Source Code Pro"
style = "Regular"

[font.bold_italic]
# family = "IosevkaRakesh Nerd Font"
family = "Annotation Mono"
style = "Regular"
