format = """
$directory\
$git_branch\
$git_status \
$character"""

add_newline = false

[directory]
style = "bold #9ccfd8"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "

[git_branch]
symbol = ""
style = "bold #c4a7e7"
format = "[\\[]($style)[$branch](#eb6f92)[\\]]($style)"

[git_status]
style = "bold #eb6f92"
format = "([$all_status$ahead_behind]($style)) "

[character]
success_symbol = "[➜ ](#ebbcba)"
error_symbol = "[➜ ](#eb6f92)"
vicmd_symbol = "[⇠ ](#f6c177)"

[package]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[python]
disabled = true
