# One Dark Pro Color Palette
set $bg             #282c34
set $bg_alt         #21252b
set $fg             #abb2bf
set $red            #e06c75
set $green          #98c379
set $yellow         #e5c07b
set $blue           #61afef
set $purple         #c678dd
set $cyan           #56b6c2
set $orange         #d19a66
set $gray           #5c6370
set $selection      #3e4452


# i3 Window Coloring (class          border          backgr.         text            indicator       child_border)
client.focused                       $purple         $purple         $bg             $blue           $purple
client.focused_inactive              $bg_alt         $bg_alt         $gray           $selection      $bg_alt
client.unfocused                     $bg             $bg             $gray           $bg_alt         $bg
client.urgent                        $red            $red            $bg             $red            $red
