-- Hyprland Lua Configuration (v0.55+)
-- Main Entry Point

-- Disable autogenerated warning
hl.config({ autogenerated = false })

-- Import modules
require("modules.monitor")
require("modules.programs")
require("modules.autostart")
require("modules.env")
require("modules.decoration")
require("modules.animations")
require("modules.windowrules")
require("modules.layouts")
require("modules.misc")
require("modules.input")
require("modules.keybinds")
