###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = nautilus
$menu = ~/.config/wofi/scripts/toggle-menu.sh
$browser = chromium-browser
$brave = brave
# $clipboard = alacritty --class clipse -e clipse
$clipboard = cliphist list | wofi --show dmenu --prompt "Clipboard" | cliphist decode | wl-copy
$bar = pkill waybar || waybar
