###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = nautilus
$menu = ulauncher
$browser = chromium-browser
$brave = brave
# $clipboard = alacritty --class clipse -e clipse
$clipboard = cliphist list | wofi --drun-print_line --show dmenu | cliphist decode | wl-copy
$bar = pkill waybar || waybar
