# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1f1f28"

# Main text color
theme[main_fg]="#dcd7ba"

# Title color for boxes
theme[title]="#dcd7ba"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7e9cd8"

# Background color of selected item in processes box
theme[selected_bg]="#2d4f67"

# Foreground color of selected item in processes box
theme[selected_fg]="#7e9cd8"

# Color of inactive/disabled text
theme[inactive_fg]="#727169"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#6a9589"

# Background color of the percentage meters
theme[meter_bg]="#2d4f67"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#957fb8"

# Cpu box outline color
theme[cpu_box]="#7e9cd8"

# Memory/disks box outline color
theme[mem_box]="#76946a"

# Net up/down box outline color
theme[net_box]="#957fb8"

# Processes box outline color
theme[proc_box]="#c34043"

# Box divider line and small boxes line color
theme[div_line]="#2d4f67"

# Temperature graph colors
theme[temp_start]="#76946a"
theme[temp_mid]="#c0a36e"
theme[temp_end]="#c34043"

# CPU graph colors
theme[cpu_start]="#76946a"
theme[cpu_mid]="#c0a36e"
theme[cpu_end]="#c34043"

# Mem/Disk free meter
theme[free_start]="#76946a"
theme[free_mid]="#76946a"
theme[free_end]="#76946a"

# Mem/Disk cached meter
theme[cached_start]="#7e9cd8"
theme[cached_mid]="#7e9cd8"
theme[cached_end]="#7e9cd8"

# Mem/Disk available meter
theme[available_start]="#7fb4ca"
theme[available_mid]="#7fb4ca"
theme[available_end]="#7fb4ca"

# Mem/Disk used meter
theme[used_start]="#957fb8"
theme[used_mid]="#957fb8"
theme[used_end]="#957fb8"

# Download graph colors
theme[download_start]="#6a9589"
theme[download_mid]="#7e9cd8"
theme[download_end]="#7e9cd8"

# Upload graph colors
theme[upload_start]="#957fb8"
theme[upload_mid]="#c34043"
theme[upload_end]="#c34043"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#7e9cd8"
theme[process_mid]="#7fb4ca"
theme[process_end]="#76946a"
