# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#282c34"

# Main text color
theme[main_fg]="#abb2bf"

# Title color for boxes
theme[title]="#abb2bf"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#61afef"

# Background color of selected item in processes box
theme[selected_bg]="#3e4452"

# Foreground color of selected item in processes box
theme[selected_fg]="#61afef"

# Color of inactive/disabled text
theme[inactive_fg]="#5c6370"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#56b6c2"

# Background color of the percentage meters
theme[meter_bg]="#3e4452"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c678dd"

# Cpu box outline color
theme[cpu_box]="#61afef"

# Memory/disks box outline color
theme[mem_box]="#98c379"

# Net up/down box outline color
theme[net_box]="#c678dd"

# Processes box outline color
theme[proc_box]="#e06c75"

# Box divider line and small boxes line color
theme[div_line]="#3e4452"

# Temperature graph colors
theme[temp_start]="#98c379"
theme[temp_mid]="#e5c07b"
theme[temp_end]="#e06c75"

# CPU graph colors
theme[cpu_start]="#98c379"
theme[cpu_mid]="#e5c07b"
theme[cpu_end]="#e06c75"

# Mem/Disk free meter
theme[free_start]="#98c379"
theme[free_mid]="#98c379"
theme[free_end]="#98c379"

# Mem/Disk cached meter
theme[cached_start]="#61afef"
theme[cached_mid]="#61afef"
theme[cached_end]="#61afef"

# Mem/Disk available meter
theme[available_start]="#56b6c2"
theme[available_mid]="#56b6c2"
theme[available_end]="#56b6c2"

# Mem/Disk used meter
theme[used_start]="#c678dd"
theme[used_mid]="#c678dd"
theme[used_end]="#c678dd"

# Download graph colors
theme[download_start]="#56b6c2"
theme[download_mid]="#61afef"
theme[download_end]="#61afef"

# Upload graph colors
theme[upload_start]="#c678dd"
theme[upload_mid]="#e06c75"
theme[upload_end]="#e06c75"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#61afef"
theme[process_mid]="#56b6c2"
theme[process_end]="#98c379"
