# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# One Dark Pro
include current-theme.conf
# END_KITTY_THEME

#: Fonts
font_family      IosevkaRakesh Nerd Font
bold_font        IosevkaRakesh Nerd Font
italic_font      IosevkaRakesh Nerd Font
bold_italic_font IosevkaRakesh Nerd Font
font_size        14.0

#: Font Rendering & Spacing
modify_font cell_height +1px
text_composition_strategy legacy

#: Window
background_opacity         0.96
background_blur            1
window_padding_width      12
hide_window_decorations    yes
confirm_os_window_close    0
wayland_titlebar_color     background
linux_display_server       wayland
remember_window_size       no
initial_window_state      fullscreen

#: Scrolling
scrollback_lines 10000
touch_scroll_multiplier 3.0

#: Shell
shell /bin/bash

#: Cursor
cursor_shape block
cursor_blink_interval 0.5

#: Mouse
mouse_hide_wait 3.0
copy_on_select yes

#: Keybindings
map alt+enter       toggle_fullscreen
map ctrl+shift+c    copy_to_clipboard
map ctrl+shift+v    paste_from_clipboard
map ctrl+plus       change_font_size all +2.0
map ctrl+minus      change_font_size all -2.0
map ctrl+0          change_font_size all 0
